export const GET_TODOS_LOADING = 'GET_TODOS_LOADING';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';
export const ADD_NEW_TODO = 'ADD_NEW_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const MARK_AS_COMPLETE = "MARK_AS_COMPLETE";
export const GET_SINGLE_TODO = 'GET_SINGLE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';