export const GET_TODOS_LOADING = 'GET_TODOS_LOADING';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';
export const ADD_NEW_TODO = 'ADD_NEW_TODO';